# Generated by Django 5.1.1 on 2024-11-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
