# Generated by Django 5.1.1 on 2024-11-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='interaction',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_interaction', to='blogs.interactions'),
            preserve_default=False,
        ),
    ]
