# Generated by Django 5.1.1 on 2024-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comments_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Followers Only'), (3, 'Public')], default=3),
        ),
    ]
