# Generated by Django 5.1.1 on 2024-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_followers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followers',
            table='followers',
        ),
    ]
